# Generated by Django 3.2.18 on 2024-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20240919_1222'),
        ('accounts', '0004_alter_user_saved_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_stories',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='story.Story'),
        ),
    ]
