# Generated by Django 3.2.18 on 2024-10-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_saved_stories'),
        ('accounts', '0005_user_old_brawna_id'),
    ]

    operations = [
    ]
