# Generated by Django 5.1.4 on 2025-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_merge_20241005_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="author_status_requested",
            field=models.BooleanField(default=False),
        ),
    ]
