# Generated by Django 5.1.4 on 2025-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_author_status_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="author_status_denied",
            field=models.BooleanField(default=False),
        ),
    ]
