# Generated by Django 3.2.18 on 2024-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_brawna_term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
