# Generated by Django 5.1.4 on 2025-08-11 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("story", "0001_initial"),
        ("story", "0002_alter_story_chapters"),
        ("story", "0003_auto_20240919_1222"),
        ("story", "0004_story_title"),
        ("story", "0005_auto_20240920_0923"),
        ("story", "0003_story_old_brawna_id"),
        ("story", "0006_merge_20241005_0002"),
        ("story", "0007_story_is_published"),
        ("story", "0008_auto_20241028_1306"),
        ("story", "0009_alter_story_categories"),
        ("story", "0012_story_old_brawna_parent_id"),
        ("story", "0010_alter_chapter_title_alter_story_brief"),
        ("story", "0011_alter_story_categories_alter_story_slug_and_more"),
        ("story", "0013_merge_20250204_2128"),
        ("story", "0011_chapter_old_brawna_parent_id"),
        ("story", "0014_merge_20250204_2130"),
        ("story", "0015_alter_chapter_body_alter_story_categories_and_more"),
        ("story", "0016_remove_chapter_story_storychapters_story_chapters"),
        ("story", "0017_alter_story_slug"),
    ]

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("category", "0005_category_old_brawna_term_id"),
        ("category", "0006_alter_category_description"),
        ("tag", "0001_initial"),
        ("tag", "0004_tag_old_brawna_term_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brief", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="category.category"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="tag.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("old_brawna_id", models.IntegerField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("has_chapters", models.BooleanField(default=False)),
                ("old_brawna_parent_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("old_brawna_id", models.IntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("old_brawna_parent_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoryChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order of this chapter within the story",
                        verbose_name="Order",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter is part of this Story",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.chapter",
                        verbose_name="Chapter",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="Chapter is part of this Story",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.story",
                        verbose_name="Story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Chapter",
                "verbose_name_plural": "Story Chapters",
                "ordering": ["order"],
                "unique_together": {("story", "chapter")},
            },
        ),
        migrations.AddField(
            model_name="story",
            name="chapters",
            field=models.ManyToManyField(
                help_text="Chapters in this Story",
                related_name="chapters",
                through="story.StoryChapters",
                to="story.chapter",
                verbose_name="Chapter",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
