# Generated by Django 3.2.18 on 2024-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='story.Story'),
        ),
    ]
