# Generated by Django 3.2.18 on 2024-10-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='old_brawna_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
