# Generated by Django 3.2.18 on 2024-10-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story_old_brawna_id'),
        ('story', '0005_auto_20240920_0923'),
    ]

    operations = [
    ]
