# Generated by Django 3.2.18 on 2024-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_merge_20241005_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
