# Generated by Django 3.2.18 on 2024-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_old_brawna_term_id'),
        ('story', '0008_auto_20241028_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.Category'),
        ),
    ]
