# Generated by Django 3.2.18 on 2024-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_story_old_brawna_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='old_brawna_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
