# Generated by Django 3.2.18 on 2024-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_story_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='old_brawna_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
