# Generated by Django 5.1.4 on 2025-02-04 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0011_alter_story_categories_alter_story_slug_and_more"),
        ("story", "0012_story_old_brawna_parent_id"),
    ]

    operations = []
