# Generated by Django 5.1.4 on 2025-02-04 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0011_chapter_old_brawna_parent_id"),
        ("story", "0013_merge_20250204_2128"),
    ]

    operations = []
