# Generated by Django 5.1.4 on 2025-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0006_alter_category_description"),
        ("story", "0014_merge_20250204_2130"),
        ("tag", "0004_tag_old_brawna_term_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="categories",
            field=models.ManyToManyField(blank=True, to="category.category"),
        ),
        migrations.AlterField(
            model_name="story",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tag.tag"),
        ),
    ]
