# Generated by Django 5.1.4 on 2025-05-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0015_alter_chapter_body_alter_story_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="story",
        ),
        migrations.CreateModel(
            name="StoryChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order of this chapter within the story",
                        verbose_name="Order",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Chapter is part of this Story",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.chapter",
                        verbose_name="Chapter",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="Chapter is part of this Story",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="story.story",
                        verbose_name="Story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Chapter",
                "verbose_name_plural": "Story Chapters",
                "ordering": ["order"],
                "unique_together": {("story", "chapter")},
            },
        ),
        migrations.AddField(
            model_name="story",
            name="chapters",
            field=models.ManyToManyField(
                help_text="Chapters in this Story",
                related_name="chapters",
                through="story.StoryChapters",
                to="story.chapter",
                verbose_name="Chapter",
            ),
        ),
    ]
