# Generated by Django 5.1.4 on 2025-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("story", "0016_remove_chapter_story_storychapters_story_chapters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
